import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import { MapPin, Phone, User, CreditCard, ShieldCheck, Loader2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { useCart } from '@/contexts/CartContext';
import { useRazorpay } from '@/hooks/useRazorpay';
import { supabase } from '@/integrations/supabase/client';
import { useToast } from '@/hooks/use-toast';
import Layout from '@/components/layout/Layout';

interface CheckoutForm {
  name: string;
  phone: string;
  email: string;
  address: string;
  city: string;
  pincode: string;
  instructions: string;
}

const Checkout = () => {
  const navigate = useNavigate();
  const { items, subtotal, clearCart, loading: cartLoading } = useCart();
  const { toast } = useToast();
  const [processing, setProcessing] = useState(false);
  const [userId, setUserId] = useState<string | null>(null);
  const [paymentMethod, setPaymentMethod] = useState<'online' | 'cod'>('online');
  const [couponCode, setCouponCode] = useState('');
  const [couponDiscount, setCouponDiscount] = useState(0);
  
  const [form, setForm] = useState<CheckoutForm>({
    name: '',
    phone: '',
    email: '',
    address: '',
    city: '',
    pincode: '',
    instructions: '',
  });

  const deliveryFee = subtotal > 500 ? 0 : 50;
  const taxBase = Math.max(0, subtotal - couponDiscount) + deliveryFee;
  const tax = taxBase * 0.05;
  const total = taxBase + tax;

  const { initiatePayment, loading: paymentLoading } = useRazorpay({
    onSuccess: async (data) => {
      await clearCart();
      navigate(`/order-success?order_id=${data.order_id}`);
    },
    onError: (error) => {
      console.error('Payment error:', error);
      setProcessing(false);
    }
  });

  useEffect(() => {
    const loadUserData = async () => {
      const { data: { session } } = await supabase.auth.getSession();
      if (!session?.user) {
        navigate('/auth');
        return;
      }
      
      setUserId(session.user.id);
      
      // Load profile data
      const { data: profile } = await supabase
        .from('profiles')
        .select('*')
        .eq('user_id', session.user.id)
        .single();

      if (profile) {
        setForm(prev => ({
          ...prev,
          name: profile.full_name || '',
          phone: profile.phone || '',
          email: profile.email || session.user.email || '',
          address: profile.address || '',
          city: profile.city || '',
          pincode: profile.pincode || '',
        }));
      }
    };

    loadUserData();
  }, [navigate]);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    setForm(prev => ({ ...prev, [e.target.name]: e.target.value }));
  };

  const validateForm = () => {
    if (!form.name || !form.phone || !form.address || !form.city || !form.pincode) {
      toast({
        title: "Missing Information",
        description: "Please fill in all required fields",
        variant: "destructive"
      });
      return false;
    }
    
    if (form.phone.length < 10) {
      toast({
        title: "Invalid Phone",
        description: "Please enter a valid phone number",
        variant: "destructive"
      });
      return false;
    }
    
    if (form.pincode.length !== 6) {
      toast({
        title: "Invalid Pincode",
        description: "Please enter a valid 6-digit pincode",
        variant: "destructive"
      });
      return false;
    }
    
    return true;
  };

  const handlePlaceOrder = async () => {
    if (!validateForm() || !userId) return;
    if (items.length === 0) {
      toast({
        title: "Cart is empty",
        description: "Please add items to your cart",
        variant: "destructive"
      });
      return;
    }

    if (paymentMethod === 'online') {
      toast({ title: 'Online payment', description: 'Coming soon', variant: 'default' });
      return;
    }

    setProcessing(true);

    try {
      // Create order in database
      // order_number is auto-generated by trigger
      const { data: order, error: orderError } = await supabase
        .from('orders')
        .insert([{
          user_id: userId,
          order_number: 'TEMP', // Will be overwritten by trigger
          subtotal,
          tax_amount: tax,
          delivery_fee: deliveryFee,
          total_amount: total,
          delivery_address: form.address,
          delivery_city: form.city,
          delivery_pincode: form.pincode,
          special_instructions: form.instructions || null,
          status: 'pending' as const,
        }])
        .select()
        .single();

      if (orderError || !order) {
        throw orderError || new Error('Order insert failed');
      }

      // Best-effort: create order items
      try {
        const orderItems = items.map(item => ({
          order_id: order.id,
          menu_item_id: item.menu_item_id,
          item_name: item.menu_item?.name || 'Unknown',
          item_price: item.menu_item?.discounted_price || item.menu_item?.price || 0,
          quantity: item.quantity,
          special_instructions: item.special_instructions,
        }));
        await supabase.from('order_items').insert(orderItems);
      } catch (itemsErr) {
        console.warn('order_items insert failed:', itemsErr);
      }

      // Best-effort: create payment record
      try {
        await supabase
          .from('payments')
          .insert({ order_id: order.id, amount: total, status: 'pending' });
      } catch (paymentErr) {
        console.warn('payment insert failed:', paymentErr);
      }

      // Update profile with delivery info (best-effort)
      await supabase
        .from('profiles')
        .update({
          full_name: form.name,
          phone: form.phone,
          email: form.email,
          address: form.address,
          city: form.city,
          pincode: form.pincode,
        })
        .eq('user_id', userId);

      if (paymentMethod === 'cod') {
        // COD: keep payment pending, clear cart and navigate to success
        toast({ title: 'Order Placed (COD)', description: 'Pay with cash upon delivery.' });
        await clearCart();
        navigate(`/order-success?order_id=${order.id}`);
      }

    } catch (error: any) {
      console.error('Order creation failed:', error);
      toast({
        title: 'Order Failed',
        description: typeof error?.message === 'string' ? error.message : 'Could not create order. Please try again.',
        variant: 'destructive',
      });
      setProcessing(false);
    }
  };

  if (cartLoading) {
    return (
      <Layout>
        <div className="min-h-screen pt-32 pb-20 flex items-center justify-center">
          <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-primary" />
        </div>
      </Layout>
    );
  }

  if (items.length === 0) {
    navigate('/cart');
    return null;
  }

  return (
    <Layout>
      <div className="min-h-screen pt-32 pb-20">
        <div className="container-custom px-4 sm:px-6 lg:px-8">
          {/* Header */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="mb-10"
          >
            <h1 className="text-4xl md:text-5xl font-display text-gradient-gold mb-4">
              Checkout
            </h1>
            <p className="text-muted-foreground">
              Complete your order details
            </p>
          </motion.div>

          <div className="grid lg:grid-cols-3 gap-8">
            {/* Delivery Form */}
            <motion.div
              initial={{ opacity: 0, x: -20 }}
              animate={{ opacity: 1, x: 0 }}
              className="lg:col-span-2"
            >
              <div className="glass-card rounded-xl p-6">
                <h2 className="font-display text-xl text-foreground mb-6 flex items-center gap-2">
                  <MapPin className="h-5 w-5 text-primary" />
                  Delivery Information
                </h2>

                <div className="grid md:grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label htmlFor="name">Full Name *</Label>
                    <div className="relative">
                      <User className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                      <Input
                        id="name"
                        name="name"
                        value={form.name}
                        onChange={handleChange}
                        className="pl-10"
                        placeholder="Your name"
                      />
                    </div>
                  </div>

                  <div className="space-y-2">
                    <Label htmlFor="phone">Phone Number *</Label>
                    <div className="relative">
                      <Phone className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                      <Input
                        id="phone"
                        name="phone"
                        value={form.phone}
                        onChange={handleChange}
                        className="pl-10"
                        placeholder="10-digit number"
                      />
                    </div>
                  </div>

                  <div className="space-y-2 md:col-span-2">
                    <Label htmlFor="email">Email (Optional)</Label>
                    <Input
                      id="email"
                      name="email"
                      type="email"
                      value={form.email}
                      onChange={handleChange}
                      placeholder="For order updates"
                    />
                  </div>

                  <div className="space-y-2 md:col-span-2">
                    <Label htmlFor="address">Delivery Address *</Label>
                    <Textarea
                      id="address"
                      name="address"
                      value={form.address}
                      onChange={handleChange}
                      placeholder="House/Flat no., Street, Landmark"
                      rows={2}
                    />
                  </div>

                  <div className="space-y-2">
                    <Label htmlFor="city">City *</Label>
                    <Input
                      id="city"
                      name="city"
                      value={form.city}
                      onChange={handleChange}
                      placeholder="City"
                    />
                  </div>

                  <div className="space-y-2">
                    <Label htmlFor="pincode">Pincode *</Label>
                    <Input
                      id="pincode"
                      name="pincode"
                      value={form.pincode}
                      onChange={handleChange}
                      placeholder="6-digit pincode"
                      maxLength={6}
                    />
                  </div>

                  <div className="space-y-2 md:col-span-2">
                    <Label htmlFor="instructions">Special Instructions (Optional)</Label>
                    <Textarea
                      id="instructions"
                      name="instructions"
                      value={form.instructions}
                      onChange={handleChange}
                      placeholder="Any special delivery instructions..."
                      rows={2}
                    />
                  </div>
                </div>
              </div>
            </motion.div>

            {/* Order Summary */}
            <motion.div
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ delay: 0.2 }}
              className="lg:col-span-1"
            >
              <div className="glass-card rounded-xl p-6 sticky top-32">
                <h2 className="font-display text-xl text-foreground mb-6">Order Summary</h2>

                {/* Items */}
                <div className="space-y-3 mb-4 max-h-48 overflow-y-auto">
                  {items.map(item => (
                    <div key={item.id} className="flex justify-between text-sm">
                      <span className="text-muted-foreground truncate max-w-[60%]">
                        {item.quantity}x {item.menu_item?.name}
                      </span>
                      <span className="text-foreground">
                        ₹{((item.menu_item?.discounted_price || item.menu_item?.price || 0) * item.quantity).toFixed(0)}
                      </span>
                    </div>
                  ))}
                </div>
                
                {/* Coupon */}
                <div className="flex gap-2 mb-4">
                  <Input
                    placeholder="Coupon code"
                    value={couponCode}
                    onChange={(e) => setCouponCode(e.target.value.toUpperCase())}
                  />
                  <Button
                    variant="outline"
                    onClick={async () => {
                      if (!couponCode) { setCouponDiscount(0); return; }
                      const { data: offers } = await supabase
                        .from('offers')
                        .select('*')
                        .ilike('code', couponCode)
                        .eq('is_active', true)
                        .limit(1);
                      const offer = offers?.[0];
                      const now = new Date();
                      if (!offer || (offer.expires_at && new Date(offer.expires_at) < now)) {
                        setCouponDiscount(0);
                        toast({ title: 'Invalid Coupon', description: 'Code is inactive or expired', variant: 'destructive' });
                        return;
                      }
                      if (offer.min_order_amount && subtotal < Number(offer.min_order_amount)) {
                        setCouponDiscount(0);
                        toast({ title: 'Minimum not met', description: `Requires minimum order ₹${offer.min_order_amount}` });
                        return;
                      }
                      let discount = 0;
                      if (offer.discount_type === 'percentage') {
                        discount = Math.round(subtotal * (Number(offer.discount_value) / 100));
                      } else {
                        discount = Math.round(Number(offer.discount_value));
                      }
                      if (offer.max_discount) discount = Math.min(discount, Number(offer.max_discount));
                      discount = Math.min(discount, Math.max(0, subtotal));
                      setCouponDiscount(discount);
                      toast({ title: 'Coupon Applied', description: `Discount ₹${discount}` });
                    }}
                  >
                    Apply
                  </Button>
                </div>

                <div className="border-t border-border pt-4 space-y-3">
                  <div className="flex justify-between text-muted-foreground">
                    <span>Subtotal</span>
                    <span>₹{subtotal.toFixed(0)}</span>
                  </div>
                  {couponDiscount > 0 && (
                    <div className="flex justify-between text-green-600">
                      <span>Coupon Discount</span>
                      <span>-₹{couponDiscount.toFixed(0)}</span>
                    </div>
                  )}
                  <div className="flex justify-between text-muted-foreground">
                    <span>Delivery Fee</span>
                    <span>{deliveryFee === 0 ? 'FREE' : `₹${deliveryFee}`}</span>
                  </div>
                  <div className="flex justify-between text-muted-foreground">
                    <span>GST (5%)</span>
                    <span>₹{tax.toFixed(0)}</span>
                  </div>
                  
                  <div className="border-t border-border pt-3">
                    <div className="flex justify-between text-lg font-display">
                      <span className="text-foreground">Total</span>
                      <span className="text-primary">₹{total.toFixed(0)}</span>
                    </div>
                  </div>
                </div>

                {/* Payment Method */}
                <div className="space-y-2 mt-4">
                  <Label className="text-sm">Payment Method</Label>
                  <div className="flex gap-2">
                    <Button
                      type="button"
                      variant={paymentMethod === 'online' ? 'gold' : 'outline'}
                      onClick={() => setPaymentMethod('online')}
                    >
                      UPI / Cards
                    </Button>
                    <Button
                      type="button"
                      variant={paymentMethod === 'cod' ? 'gold' : 'outline'}
                      onClick={() => setPaymentMethod('cod')}
                    >
                      Cash on Delivery
                    </Button>
                  </div>
                </div>

                <Button 
                  variant="gold" 
                  size="lg" 
                  className="w-full mt-6"
                  onClick={handlePlaceOrder}
                  disabled={processing || paymentLoading}
                >
                  {processing || paymentLoading ? (
                    <>
                      <Loader2 className="mr-2 h-5 w-5 animate-spin" />
                      Processing...
                    </>
                  ) : (
                    <>
                      <CreditCard className="mr-2 h-5 w-5" />
                      Proceed to Payment
                    </>
                  )}
                </Button>

                <div className="flex items-center justify-center gap-2 mt-4 text-xs text-muted-foreground">
                  <ShieldCheck className="h-4 w-4 text-primary" />
                  Secure payment by Razorpay
                </div>
              </div>
            </motion.div>
          </div>
        </div>
      </div>
    </Layout>
  );
};

export default Checkout;
